-- Подключаемся к pluggable database
ALTER SESSION SET CONTAINER = XEPDB1;


 -- Включаем Supplemental Logging
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- Создание tablespace
CREATE TABLESPACE logminer_tbs DATAFILE 'logminer_tbs.dbf' SIZE 25M AUTOEXTEND ON;

-- Создание пользователя
CREATE USER dbz IDENTIFIED BY dbz
  DEFAULT TABLESPACE logminer_tbs
  QUOTA UNLIMITED ON logminer_tbs;

-- Выдача прав
GRANT CREATE SESSION TO dbz;
GRANT SELECT ON V_$DATABASE TO dbz;
GRANT FLASHBACK ANY TABLE TO dbz;
GRANT SELECT ANY TABLE TO dbz;
GRANT SELECT_CATALOG_ROLE TO dbz;
GRANT EXECUTE_CATALOG_ROLE TO dbz;
GRANT SELECT ANY TRANSACTION TO dbz;
GRANT LOGMINING TO dbz;
GRANT EXECUTE ON DBMS_LOGMNR TO dbz;
GRANT EXECUTE ON DBMS_LOGMNR_D TO dbz;
GRANT SELECT ON V_$LOG TO dbz;
GRANT SELECT ON V_$LOG_HISTORY TO dbz;
GRANT SELECT ON V_$LOGMNR_LOGS TO dbz;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO dbz;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO dbz;
GRANT SELECT ON V_$LOGFILE TO dbz;
GRANT SELECT ON V_$ARCHIVED_LOG TO dbz;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO dbz;
