-- Переключение в нужный контейнер базы
ALTER SESSION SET CONTAINER = XEPDB1;

-- Установка схемы по умолчанию
ALTER SESSION SET CURRENT_SCHEMA = dbz;

-- Создание таблицы (если не существует)
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE mytable (
      id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      name VARCHAR2(50),
      ts   TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN -- ORA-00955: имя уже используется
      RAISE;
    END IF;
END;
/

-- Вставка тестовых данных
BEGIN
  INSERT INTO mytable (name) VALUES ('Alice');
  INSERT INTO mytable (name) VALUES ('Bob');
  COMMIT;
END;
/
