version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin 

      KC_DB: postgres
      KC_DB_URL_HOST: postgres-container
      KC_DB_URL_PORT: 5433
      KC_DB_URL_DATABASE: keycloak-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public

      # KC_HOSTNAME: "185.56.162.137"
      # # KC_HOSTNAME_ADMIN: localhost
      # KC_HOSTNAME_STRICT: "false"
      # KC_HOSTNAME_STRICT_HTTPS: "false"
      # KC_DISABLE_FEATURES: "admin-fine-grained-authz" # disable fine-grained authz
      # KC_PROXY_ENABLED: "true"
      # KC_PROXY_PORT: 8080
      # KC_PROXY_PROTOCOL: http
      # KC_PROXY_SSL: none 
      # # KC_PROXY_HEADERS: xforwarded
      # KC_PROXY: edge      
      # KC_HTTP_ENABLED: "true"
      # # KC_HTTP_PORT: 8080
      # KC_METRICS_ENABLED: "true"
      

    command: start-dev       

    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - keycloak-network
      - infrastructure_infrastructure  # подключаем вторую сеть

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    networks:
      - keycloak-network

    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
      - vault
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge 
  
  infrastructure_infrastructure:         
    external: true 