version: '3.9'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault 
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    # command: vault server -dev
    command: vault server -config=/vault/config/vault.hcl
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
    
    ports:
      - "8200:8200"
    networks:
      - infrastructure_infrastructure  # подключаем вторую сеть
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin 

      KC_DB: postgres
      KC_DB_URL_HOST: postgres-container
      KC_DB_URL_PORT: 5433
      KC_DB_URL_DATABASE: keycloak-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public 

    command: start-dev       

    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - infrastructure-network
      - infrastructure_infrastructure  # подключаем вторую сеть

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - infrastructure-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak


networks:
  infrastructure-network:
    name: infrastructure-network
    driver: bridge 

  infrastructure_infrastructure:
      external: true 
