version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin 

      KC_DB: postgres
      KC_DB_URL_HOST: postgres-container
      KC_DB_URL_PORT: 5433
      KC_DB_URL_DATABASE: keycloak-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public

    command: >
      start-dev
      --http-enabled=true
      --proxy=edge
      --hostname-strict=false
      --hostname-strict-https=false

    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - keycloak-network
      - infrastructure_infrastructure  # подключаем вторую сеть

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge 
  
  infrastructure_infrastructure:         
    external: true 