version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault 
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    # command: vault server -dev
    command: vault server -config=/vault/config/vault.hcl
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
    
    ports:
      - "8200:8200"
    networks:      
      - infrastructure_infrastructure  # подключаем вторую сеть
  
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - vault

  networks:
    infrastructure_infrastructure:
         external: true 
