create table KLB_ROLES
(
    ID        NUMBER        not null
        constraint XPK_KLB_ROLES
            primary key,
    NAME      VARCHAR2(160) not null,
    ACCESS_ID NUMBER(2)
        constraint XFK_KLB_ROLES
            references SS_KLB_ROLE_ACCESS
)
/

create unique index XUK_KLB_ROLES
    on KLB_ROLES (NAME)
/

INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (41, 'Создать', 1);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (241, 'OOOACETIC ACID', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (221, 'Директор Отправить в банке', 1);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (1, 'Полный доступ', 3);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (2, 'Бухгалтер', 1);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (261, 'AAA', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (141, 'Просмотр', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (201, 'Бухгалтер Утвердить', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (202, 'Директор  Утвердить & Отправить в банке', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (301, 'Заявка на операции с ин.валютой', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (401, 'Online kredit', 3);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (282, 'Iteca B', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (283, 'Iteca buh', 1);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (321, 'test', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (361, 'HUMO test', 3);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (281, 'Iteca Buhgalter', 3);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (341, 'Test M Go', 3);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (381, 'ELP test', 3);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (421, 'Kafolot', 0);
INSERT INTO INETBANK.KLB_ROLES (ID, NAME, ACCESS_ID) VALUES (441, 'Просмотр кредит', 0);
