create table MODULES_ACT
(
    MODULE_ID NUMBER not null
        constraint XFK_MODULE_ACTIONS
            references MODULES
                on delete cascade,
    ACTION_ID NUMBER not null,
    VALUE     VARCHAR2(32),
    ID        NUMBER
        constraint XUK_MODULE_ACTIONS
            unique,
    constraint XPK_MODULE_ACTIONS
        primary key (MODULE_ID, ACTION_ID)
)
/

INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (208, 1, 'Создание ЗП ведомостей', 18);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (208, 0, 'Просмотр', 17);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (206, 0, 'Вкл/откл', 11);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (201, 0, 'Просмотр', 1);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (201, 1, 'Создание платежей', 2);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (202, 0, 'Просмотр', 3);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (203, 0, 'Управление шаблонами', 4);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (204, 0, 'Нет отчетов', 5);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (204, 1, 'Выписка', 6);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (204, 2, 'Справка о работе счёта', 7);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (205, 0, 'Нет справочников', 8);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (205, 1, 'МФО', 9);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (205, 2, 'Коды назначение платежей', 10);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (207, 2, 'Проверка', 15);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (207, 3, 'Утверждение', 16);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (207, 0, 'Просмотр', 13);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (207, 1, 'Ввод', 14);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (201, 2, 'Отправка на подпись', 12);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (212, 0, 'Просмотр', 25);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (103, 0, 'Просмотр', 103);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (209, 0, 'Просмотр', 19);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (209, 1, 'Создание заявок', 20);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (210, 0, 'Просмотр', 21);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (210, 1, 'Выписка', 22);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (211, 0, 'Просмотр', 23);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (211, 1, 'Создание платежей', 24);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (214, 1, 'Подключение услуг инкассации', 21401);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (208, 2, 'Создание ЗП ведомостей HUMO', 218);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (208, 3, 'Создание ЗП ведомостей UPI', 219);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (215, 0, 'Просмотр', 2150);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (215, 1, 'Создание требований', 2151);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (215, 2, 'Оприходование в К1', 2152);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (216, 0, 'Просмотр', 2160);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (216, 1, 'Акцептование', 2161);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (216, 2, 'Отклонение', 2162);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (216, 3, 'Частичная оплата', 2163);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (216, 4, 'Продление', 2164);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (217, 0, 'Просмотр', 102170);
INSERT INTO MOBILE.MODULES_ACT (MODULE_ID, ACTION_ID, VALUE, ID) VALUES (217, 1, 'Создание заявки', 102171);
