version: '3.9'

services: 
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - infrastructure-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  

networks: 
  keycloak-network:
    external: true

  infrastructure-network:
    external: true 
