version: '3.9'

services: 

 vault:
    image: hashicorp/vault:1.15
    container_name: vault 
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    # command: vault server -dev
    command: vault server -config=/vault/config/vault.hcl
    volumes:
      - redis-data:/vault/config/vault.hcl:ro    
    ports:
      - "8200:8200"
    networks:
      - infrastructure-network 
 keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin 

      KC_DB: postgres
      KC_DB_URL_HOST: postgres-container
      KC_DB_URL_PORT: 5433
      KC_DB_URL_DATABASE: keycloak-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public 

    command: start-dev       

    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - infrastructure-network   
      
networks: 
  keycloak-network:
    name: keycloak-network
    driver: bridge

  infrastructure-network:
      external: true 

volumes:
  vault-data: