version: '3.9'

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deploy:/data
    environment:
      DOZZLE_AUTH_PROVIDER: simple

networks:
  infrastructure-network:
    name: infrastructure-network
    driver: bridge