-- Создание пользователя для тестирования
CREATE USER INETBANK IDENTIFIED BY test_password;

-- Предоставление базовых прав
GRANT CREATE SESSION TO INETBANK;
GRANT CONNECT TO INETBANK;
GRANT RESOURCE TO INETBANK;
GRANT CREATE TABLE TO INETBANK;
GRANT UNLIMITED TABLESPACE TO INETBANK;

-- Создание роли для LogMiner
CREATE ROLE logminer_role;
GRANT CREATE SESSION TO logminer_role;
GRANT SET CONTAINER TO logminer_role;
GRANT SELECT ON V_$DATABASE TO logminer_role;
GRANT FLASHBACK ANY TABLE TO logminer_role;
GRANT SELECT ANY TABLE TO logminer_role;
GRANT SELECT_CATALOG_ROLE TO logminer_role;
GRANT EXECUTE_CATALOG_ROLE TO logminer_role;
GRANT SELECT ANY TRANSACTION TO logminer_role;
GRANT SELECT ANY DICTIONARY TO logminer_role;
GRANT LOGMINING TO logminer_role;

-- Предоставление роли пользователю
GRANT logminer_role TO INETBANK;

-- Дополнительные права для работы с LogMiner
GRANT SELECT ON V_$DATABASE TO INETBANK;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO INETBANK;
GRANT SELECT ON V_$ARCHIVED_LOG TO INETBANK;
GRANT SELECT ON V_$LOG TO INETBANK;
GRANT SELECT ON V_$LOGFILE TO INETBANK;
GRANT SELECT ON V_$LOGMNR_LOGS TO INETBANK;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO INETBANK;
GRANT SELECT ON V_$LOGMNR_PROCESS TO INETBANK;
GRANT SELECT ON V_$LOGMNR_SESSION TO INETBANK;
GRANT SELECT ON V_$LOGMNR_STATS TO INETBANK;
GRANT SELECT ON V_$LOGMNR_TRANSACTION TO INETBANK;

-- Проверка и создание таблицы
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'INETBANK';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE INETBANK.test_table (
      id NUMBER PRIMARY KEY,
      name VARCHAR2(100),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP
    )';
    
    EXECUTE IMMEDIATE 'INSERT INTO INETBANK.test_table (id, name) VALUES (1, ''Test 1'')';
    EXECUTE IMMEDIATE 'INSERT INTO INETBANK.test_table (id, name) VALUES (2, ''Test 2'')';
    EXECUTE IMMEDIATE 'INSERT INTO INETBANK.test_table (id, name) VALUES (3, ''Test 3'')';
    
    COMMIT;
    
    -- Дополнительные права для Debezium
    EXECUTE IMMEDIATE 'GRANT SELECT ON INETBANK.test_table TO INETBANK';
    EXECUTE IMMEDIATE 'GRANT FLASHBACK ON INETBANK.test_table TO INETBANK';
  END IF;
END;
/ 