-- Создание пользователя для тестирования
CREATE USER MOBILE IDENTIFIED BY test_password;

-- Предоставление базовых прав
GRANT CREATE SESSION TO MOBILE;
GRANT CONNECT TO MOBILE;
GRANT RESOURCE TO MOBILE;
GRANT CREATE TABLE TO MOBILE;
GRANT UNLIMITED TABLESPACE TO MOBILE;

-- Создание роли для LogMiner
CREATE ROLE logminer_role;
GRANT CREATE SESSION TO logminer_role;
GRANT SET CONTAINER TO logminer_role;
GRANT SELECT ON V_$DATABASE TO logminer_role;
GRANT FLASHBACK ANY TABLE TO logminer_role;
GRANT SELECT ANY TABLE TO logminer_role;
GRANT SELECT_CATALOG_ROLE TO logminer_role;
GRANT EXECUTE_CATALOG_ROLE TO logminer_role;
GRANT SELECT ANY TRANSACTION TO logminer_role;
GRANT SELECT ANY DICTIONARY TO logminer_role;
GRANT LOGMINING TO logminer_role;

-- Предоставление роли пользователю
GRANT logminer_role TO MOBILE;

-- Дополнительные права для работы с LogMiner
GRANT SELECT ON V_$DATABASE TO MOBILE;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO MOBILE;
GRANT SELECT ON V_$ARCHIVED_LOG TO MOBILE;
GRANT SELECT ON V_$LOG TO MOBILE;
GRANT SELECT ON V_$LOGFILE TO MOBILE;
GRANT SELECT ON V_$LOGMNR_LOGS TO MOBILE;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO MOBILE;
GRANT SELECT ON V_$LOGMNR_PROCESS TO MOBILE;
GRANT SELECT ON V_$LOGMNR_SESSION TO MOBILE;
GRANT SELECT ON V_$LOGMNR_STATS TO MOBILE;
GRANT SELECT ON V_$LOGMNR_TRANSACTION TO MOBILE;

-- Проверка и создание таблицы
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'MOBILE';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE MOBILE.test_table (
      id NUMBER PRIMARY KEY,
      name VARCHAR2(100),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP
    )';
    
    EXECUTE IMMEDIATE 'INSERT INTO MOBILE.test_table (id, name) VALUES (1, ''Test 1'')';
    EXECUTE IMMEDIATE 'INSERT INTO MOBILE.test_table (id, name) VALUES (2, ''Test 2'')';
    EXECUTE IMMEDIATE 'INSERT INTO MOBILE.test_table (id, name) VALUES (3, ''Test 3'')';
    
    COMMIT;
    
    -- Дополнительные права для Debezium
    EXECUTE IMMEDIATE 'GRANT SELECT ON MOBILE.test_table TO MOBILE';
    EXECUTE IMMEDIATE 'GRANT FLASHBACK ON MOBILE.test_table TO MOBILE';
  END IF;
END;
/ 