create table organizations
(
    id           integer generated by default as identity
        constraint pk_organizations
            primary key,
    client       varchar(50)  not null,
    branch       varchar(50)  not null,
    name         varchar(200) not null,
    tarif        varchar(100) not null,
    state        integer      not null,
    created_date timestamp    not null
);

alter table organizations
    owner to "mfb-user";

INSERT INTO public.organizations (id, client, branch, name, tarif, state, created_date) VALUES (1, '00000444', '00444', 'superorg', '1', 0, '-infinity');
