create table roles
(
    id              integer generated by default as identity
        constraint pk_roles
            primary key,
    description     varchar(500)            not null,
    name            varchar(100)            not null,
    role_type       integer                 not null,
    state           integer   default 2     not null,
    organization_id integer                 not null
        constraint fk_roles_organizations_organization_id
            references organizations
            on delete restrict,
    created_date    timestamp default now() not null
);

alter table roles
    owner to "mfb-user";

create index ix_roles_organization_id
    on roles (organization_id);

INSERT INTO public.roles (id, description, name, role_type, state, organization_id, created_date) VALUES (1, 'Some Role Description', 'Super-Admin', 1, 2, 1, '2025-05-28 06:29:50.751543');
