create table user_mobiles
(
    id              integer generated by default as identity
        constraint pk_user_mobiles
            primary key,
    login           varchar(100) not null,
    name            varchar(200) not null,
    password        text         not null,
    salt            varchar(50),
    email           varchar(100),
    state           integer      not null,
    last_login      timestamp,
    type            integer      not null,
    password_format integer      not null,
    passport        varchar(50),
    attempts        integer      not null,
    sc_base64       text         not null,
    sc_attempts     integer      not null,
    phrase          varchar(255),
    sign_method     integer      not null,
    branch          varchar(100) not null,
    ip              varchar(50),
    pincode         varchar(32),
    role_id         integer      not null
        constraint fk_user_mobiles_roles_role_id
            references roles
            on delete restrict,
    created_date    timestamp    not null
);

alter table user_mobiles
    owner to "mfb-user";

create index ix_user_mobiles_email
    on user_mobiles (email);

create unique index ix_user_mobiles_login
    on user_mobiles (login);

create index ix_user_mobiles_role_id
    on user_mobiles (role_id);

INSERT INTO public.user_mobiles (id, login, name, password, salt, email, state, last_login, type, password_format, passport, attempts, sc_base64, sc_attempts, phrase, sign_method, branch, ip, pincode, role_id, created_date) VALUES (1, 'superadmin', 'superadmin', 'QynwXp+rm59MrBFFz15MB8yA4cA=', 'Qu1o3oFRWD8YHWDSQAg8ty8tdQ5IJgfZ', 'superadmin@email.com', 1, '2025-05-28 06:29:50.751542', 1, 1, 'AA1234567', 0, '', 0, 'superadminphrase', 2, '00444', '127.0.0.1', '81dc9bdb52d04dc20036dbd8313ed055', 1, '2025-05-28 06:29:50.751542');
