users:
  admin:
    email: admin@example.com
    name: Admin
    password: $2a$11$ipZjN8LJIwfgGk7nXX/LjecDHYAzic0aVxu0r1GdohYEXVTQ7R2M2
  guest:
    email: guest@example.com
    name: Guest
    password: $2a$11$ZO4.koft5zmqF4TM3dJgpuCsJqXW7CrYh.cwzNN3uz6bWO9qBpPdW 