
services:
  oracle-free-local:
    image: gvenzl/oracle-free:latest
    container_name: oracle-free-local
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
      - APP_USER=mobile
      - APP_USER_PASSWORD=mobile123
    ports:
      - "1522:1521"
    volumes:
      - oracle-free-data-local:/opt/oracle/oradata
      - oracle-free-archive-local:/opt/oracle/oradata/FREE/archive
      - ./oracle/init:/docker-entrypoint-initdb.d/startup
      - ./oracle/data:/docker-entrypoint-initdb.d/data
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/oracle@//localhost:1521/FREEPDB1", "AS", "SYSDBA", "@?/rdbms/admin/utlrp.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - debezium-network
    command: >
      bash -c "
        echo 'Starting Oracle Database 23c Free...' &&
        /opt/oracle/runOracle.sh &&
        sleep 60 &&
        sqlplus -s system/oracle@//localhost:1521/FREEPDB1 AS SYSDBA <<EOF
        ALTER DATABASE ARCHIVELOG;
        ALTER DATABASE FORCE LOGGING;
        ALTER SYSTEM SET log_archive_dest_1='LOCATION=/opt/oracle/oradata/FREE/archive' SCOPE=MEMORY;
        ALTER SYSTEM SET log_archive_max_processes=4 SCOPE=MEMORY;
        ALTER SYSTEM ARCHIVE LOG CURRENT;
        SELECT log_mode FROM v\$database;
        SELECT name, value FROM v\$parameter WHERE name LIKE 'log_archive%';
        EXIT;
        EOF
        echo 'Oracle Database is ready for CDC!' &&
        tail -f /opt/oracle/diag/rdbms/free/FREE/trace/alert_FREE.log
      "

  zookeeper-local:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper-local
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - debezium-network

  kafka-local:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-local
    depends_on:
      - zookeeper-local
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-local:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - debezium-network

  kafka-connect-local:
    image: debezium/connect:2.5
    container_name: kafka-connect-local
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    depends_on:
      oracle-free-local:
        condition: service_healthy
      kafka-local:
        condition: service_started
    networks:
      - debezium-network

  kafka-ui-local:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-local
    ports:
      - "80:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka-local
    networks:
      - debezium-network

networks:
  debezium-network:
    driver: bridge

  infrastructure-network:
    driver: bridge 

volumes:
  oracle-free-data-local:
  oracle-free-archive-local: 