
services:
  admin-sync-service:
    container_name: admin-sync-service
    image: ghcr.io/akrasnikov79/admin-sync-service:latest
    ports:
      - "80:80" 
    volumes: 
      - admin-sync-service-data:/opt/admin-sync/admin-sync-data
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Stage
      - TZ=Asia/Karachi
    restart: always
    networks:
      - infrastructure-network
     

volumes:
  admin-sync-service-data: 

networks:
  infrastructure-network:
    external: true 
  
  docker-elk_elk:
    external: true
  
  elk:
    external: true
